<?php

namespace App\Http\Requests\ShopBooksApiController;

use Illuminate\Foundation\Http\FormRequest;

class AddBook_FormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return array
        (
            'appellation' => 'required',
            'year' => 'required',
            'authors' => 'required',
            'genres' => 'required'
        );
    }

    function validated(): array
    {
        $arrayParametersValidated = parent::validated(); // TODO: Change the autogenerated stub
        $arrayParametersValidated['authors'] = json_encode($arrayParametersValidated['authors']);
        $arrayParametersValidated['genres'] = json_encode($arrayParametersValidated['genres']);

        return $arrayParametersValidated;
    }
}
