<?php

namespace App\Http\Requests\ShopBooksApiController;

use Illuminate\Foundation\Http\FormRequest;

class GetPopulateBooks_FormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return array
        (
            "date_from" => "required",
            "date_to" => "required",
            "genre_appellation" => 'nullable|string',
            "limit" => 'nullable|integer'
        );
    }

    function validated(): array
    {
        $arrayParametersValidated = parent::validated(); // TODO: Change the autogenerated stub
        if (!isset($arrayParametersValidated['limit']))
            $arrayParametersValidated['limit'] = 5;

        return $arrayParametersValidated;
    }
}
