<?php

namespace App\Http\Requests\ShopBooksApiController;

use Illuminate\Foundation\Http\FormRequest;

class GetPopulateBooks_FormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return array
        (
            "date_from" => "required|date_format:Y-m-d H:i:s", # 2025-02-01 18:25:01
            "date_to" => "required|date_format:Y-m-d H:i:s",
            "genre_appellation" => 'nullable|string',
            "genre_id" => 'nullable|integer',
            "limit" => 'nullable|integer'
        );
    }

    function validated(): array
    {
        $arrayParametersValidated = parent::validated(); // TODO: Change the autogenerated stub
        if (!isset($arrayParametersValidated['limit']))
            $arrayParametersValidated['limit'] = 5;

        # Замена id жанра на название
        if (isset($arrayParametersValidated['genre_id'])):
            $collectionGenres = \App\Models\Genre::where('id', $arrayParametersValidated['genre_id'])
                ->select('appellation')->get();

            if (!$collectionGenres->isEmpty())
                $arrayParametersValidated["genre_appellation"] =
                    $collectionGenres->first()
                        ->getAttributeValue('appellation');
        endif;

        return $arrayParametersValidated;
    }
}
